function [ result_quat ] = quat_mult2( q1, q2 )
%UNTITLED5 Summary of this function goes here
%   Detailed explanation goes here

  mult_mat = [q1(1) -q1(2) -q1(3) -q1(4);...
                q1(2)  q1(1) q1(4)  -q1(3);...
                q1(3)  -q1(4)  q1(1) q1(2);...
                q1(4) q1(3)  -q1(2)  q1(1);...
                ];
            result_quat = (mult_mat*q2')';
end

